apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-1.0
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      stage: blue
  template:
    metadata:
      labels:
        app: nginx
        stage: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80