---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-dev
  namespace: coro-config
spec:
  interval: 3m0s
  path: ./gitops-fluxcd/fleet/apps/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: coro

