---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghcr-charts
spec:
  interval: 5m
  type: "oci"
  url: oci://ghcr.io/romerve/charts
  secretRef:
    name: ghcr-charts