---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rvlabscr
spec:
  interval: 5m
  type: "oci"
  url: oci://rvlabs.azurecr.io/charts
  secretRef:
    name: rvlabsacr