---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: coro-config
      version: '>5.0.0'
  interval: 1m0s
  releaseName: podinfoete
  values:
    cache: tcp://redis-master.redis:6379
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi

