---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: coro-config
spec:
  interval: 5m0s
  dependsOn:
    - name: infra
  path: ./gitops-fluxcd/fleet/apps/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: azurenaut

