apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-azure-voting
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: ghcr-charts
        namespace: coro-config
      version: '>=0.1.0'
  test:
    enable: false
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/charts/azure-voting
      tag: "0.1.1"