apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-azure-voting
spec:
  chart:
    spec:
      version: ">=0.1.0"
  test:
    enable: false
  values:
    replicaCount: 1