apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-helm-azurenaut
resources:
  - prod-ns.yaml
  - ../../base/helm-azure-voting
patchesStrategicMerge:
  - voting-patch.yaml
commonLabels:
  appenv: prod-helm