apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy-v1.0
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
      stage: green
  template:
    metadata:
      labels:
        app: httpd
        stage: green
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80