apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-azurenaut
resources:
  - dev-ns.yaml
  - ../base
patchesStrategicMerge:
  - voting-patch.yaml
commonLabels:
  appenv: dev