# This is a basic workflow to help you get started with Actions

name: CI Container App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ 9-cloudnative-fusionteams ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    environment: rvlabs-dev-env
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Azure login via SP
      - name: Azure Login
        uses: Azure/login@v1.4.4
        with:
          creds: ${{ secrets.RVLABS_AZURE_CREDENTIALS }}
          
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.6
        with:
          # Specify the script here
          inlineScript: |
            az deployment group create \
              -g ${{ RVLABS_AZ_DEV_RG }} \
              -f ./${{ RVLABS_AZ_DEV_HWAPP }} \
              -p \
                environment_name="${{ RVLABS_AZ_DEV_ENV_NAME }}" \
                location="${{ RVLABS_AZ_DEV_LOCATION }}" \
                storage_account_name="${{ RVLABS_AZ_DEV_STORAGE }}" \
                storage_container_name="${{ RVLABS_AZ_DEV_STORAGE_CONTAINER }}"
